version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
  pre_build:
    commands:
      - npm install
      - npm run build --if-present
  build:
    commands:
      - echo "Build phase"
artifacts:
  files: '**/*'
